"""
Curated script library: 50 top American political topics with full email and call scripts.
Progressive, topic-specific, constituent pressure on Congress. Used when Gemini is not available or for demo.

Messaging is tuned for impact with congressional staff (see docs/STAFFER_MESSAGING_RESEARCH.md):
- Call scripts start with "I'm a constituent from [your city or state]" so callers are ready when staff ask.
- One clear ask per script; short and polite. Email ~7–10 sentences; calls under 5 minutes.
- Users should add name/full address in contact forms so offices can verify constituency.
"""
# Each entry: title, issue_slug, subject, body (short summary), email_body (full), call_script (full)

SCRIPT_LIBRARY = [
    {
        "title": "Restore EPA climate authority — oppose GHG endangerment rescission",
        "issue_slug": "climate",
        "subject": "Urgent: Restore EPA authority to regulate greenhouse gas emissions",
        "body": "On Feb 12, 2026, EPA rescinded the 2009 endangerment finding and all motor vehicle GHG standards. Ask Congress to restore EPA authority and hold oversight.",
        "email_body": "I am a constituent writing to urge you to take action against the EPA's February 12, 2026 rescission of the Greenhouse Gas Endangerment Finding and all motor vehicle emission standards. This removes the legal foundation for EPA to regulate greenhouse gas emissions from vehicles and undermines our ability to address the climate crisis.\n\nPlease support legislation to restore EPA's authority to regulate GHG emissions, hold oversight hearings on this reckless decision, and consider using the Congressional Review Act to overturn the rule. Congress must act—we cannot allow this rollback to stand.\n\nThank you for your service. I will be paying attention to how you respond.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to take action against the EPA's recent rescission of the greenhouse gas endangerment finding and vehicle emission standards. Please support legislation to restore EPA authority and hold oversight hearings. Thank you for your time.",
    },
    {
        "title": "Oppose SAVE Act — protect voting rights",
        "issue_slug": "voting-rights",
        "subject": "Oppose the SAVE America Act — it would disenfranchise millions of voters",
        "body": "The SAVE Act passed the House 218-213 on Feb 11, 2026. It requires proof of citizenship and strict ID (student IDs excluded), disenfranchising millions. Oppose it in the Senate.",
        "email_body": "I am a constituent writing to urge you to oppose the SAVE America Act, which passed the House on February 11, 2026. The bill would require proof of citizenship (passport or birth certificate) to register to vote and impose strict photo ID requirements that exclude student IDs. Voting rights experts estimate it could disenfranchise 21 million Americans who lack these documents—disproportionately poor and minority voters.\n\nNoncitizen voting is already illegal and extremely rare. Please oppose this voter suppression bill in the Senate and support federal standards that expand access to the ballot instead.\n\nThank you for protecting our democracy.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to oppose the SAVE America Act that passed the House. It would require proof of citizenship and strict ID to vote and disenfranchise millions of Americans. Please vote no in the Senate. Thank you.",
    },
    {
        "title": "Support affordable healthcare — restore ACA subsidies",
        "issue_slug": "healthcare",
        "subject": "Support affordable healthcare — restore ACA subsidies and lower drug costs",
        "body": "ACA subsidies expired at end of 2025; premiums have more than doubled. Congress is stalled over abortion provisions. Support restoring premium tax credits without restrictive amendments.",
        "email_body": "I am a constituent writing to ask you to support affordable healthcare. The enhanced ACA premium tax credits expired at the end of 2025, and premiums have more than doubled for millions of enrollees. Congress is currently deadlocked—some want to attach abortion restrictions to subsidy legislation. Please support restoring the premium tax credits so families can afford coverage, and protect the ACA from efforts to weaken it. Also support Medicare drug negotiation and lower prescription costs.\n\nHealthcare is a right. Don't let politics block relief for millions. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support restoring ACA premium subsidies that expired in 2025. Premiums have doubled—please support legislation to extend the tax credits without abortion restrictions. Thank you.",
    },
    {
        "title": "Pass the Women's Health Protection Act — codify abortion rights",
        "issue_slug": "abortion",
        "subject": "Co-sponsor the Women's Health Protection Act (H.R. 12) — codify Roe",
        "body": "Pass the Women's Health Protection Act (H.R. 12) to codify the right to abortion in federal law and override state bans.",
        "email_body": "I am a constituent writing to urge you to co-sponsor and support the Women's Health Protection Act (H.R. 12). This bill would codify the right to access abortion care into federal law, protecting providers and patients from state bans and medically unnecessary restrictions. Politicians should not control our bodies or our decisions.\n\nPlease co-sponsor H.R. 12 and work to pass it. Stand with the majority of Americans who support reproductive rights. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to co-sponsor the Women's Health Protection Act, H.R. 12, to codify abortion rights into federal law. Thank you.",
    },
    {
        "title": "Support federal red flag law — gun violence prevention",
        "issue_slug": "gun-violence",
        "subject": "Co-sponsor the Federal Extreme Risk Protection Order Act of 2026",
        "body": "A federal red flag bill was reintroduced Feb 12, 2026. Support it to establish nationwide extreme-risk protection orders and save lives.",
        "email_body": "I am a constituent writing to ask you to co-sponsor and support the Federal Extreme Risk Protection Order Act of 2026, reintroduced on February 12. This legislation would establish nationwide access to red flag laws, allowing law enforcement and family members to temporarily remove firearms from individuals who pose a danger to themselves or others. Twenty-two states and DC already have such laws—Congress should make this protection available everywhere.\n\nPlease support this life-saving gun safety legislation. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support the Federal Extreme Risk Protection Order Act—the federal red flag bill reintroduced in February. Please co-sponsor it. Thank you.",
    },
    {
        "title": "Immigration reform",
        "issue_slug": "immigration",
        "subject": "Support humane immigration reform and a path to citizenship",
        "body": "Support humane immigration reform and a path to citizenship.",
        "email_body": "I am a constituent writing to ask you to support humane immigration reform and a path to citizenship for undocumented immigrants who contribute to our communities. Please oppose cruel enforcement-only approaches and support protecting Dreamers, reuniting families, and treating immigrants with dignity. Our country is stronger when we welcome those who seek a better life.\n\nThank you for considering my views.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support immigration reform and a path to citizenship. Please protect Dreamers and support humane policies. Thank you.",
    },
    {
        "title": "Economy and jobs",
        "issue_slug": "economy-jobs",
        "subject": "Support working families and good jobs",
        "body": "Support policies that create good jobs and strengthen working families.",
        "email_body": "I am a constituent writing to ask you to support policies that create good jobs and strengthen working families. Please back investments in infrastructure, manufacturing, and green jobs; strengthen labor rights; and ensure workers share in economic growth. Too many families are one paycheck away from crisis—Congress should be on their side.\n\nThank you for fighting for working people.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support good jobs and working families—infrastructure, labor rights, and shared prosperity. Thank you.",
    },
    {
        "title": "Inflation and cost of living",
        "issue_slug": "inflation",
        "subject": "Lower costs for families and crack down on price gouging",
        "body": "Support lowering costs and holding corporations accountable for price gouging.",
        "email_body": "I am a constituent writing to ask you to address the cost of living and stand up to corporate price gouging. Please support policies that lower costs for housing, healthcare, and essentials—and hold companies accountable when they raise prices unfairly. Working families need relief, not more giveaways to big corporations.\n\nThank you for listening.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to lower costs for families and crack down on price gouging. Please support real relief for working people. Thank you.",
    },
    {
        "title": "Restore student debt relief — SAVE ended, forgiveness now taxable",
        "issue_slug": "student-debt",
        "subject": "Restore income-driven relief and extend tax exemption for student loan forgiveness",
        "body": "SAVE plan ended; loan forgiveness is taxable again in 2026. Support restoring affordable repayment and extending the tax exemption.",
        "email_body": "I am a constituent writing to ask you to restore student debt relief. In 2026, the SAVE income-driven repayment plan was discontinued, forcing 7.5 million borrowers to switch. In addition, the tax exemption for student loan forgiveness expired—borrowers now owe taxes on forgiven amounts. Please support legislation to extend the tax exemption for forgiveness and restore affordable income-driven repayment options so borrowers aren't crushed by debt.\n\nI urge you to stand with students and borrowers. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to restore student debt relief—extend the tax exemption for forgiveness and support affordable repayment plans. Thank you.",
    },
    {
        "title": "Public education funding",
        "issue_slug": "education",
        "subject": "Fully fund public education and support teachers",
        "body": "Support full funding for public schools and respect for educators.",
        "email_body": "I am a constituent writing to ask you to fully fund public education and support teachers and staff. Please oppose vouchers that drain resources from public schools and support federal investment in K–12 so every child has a great education regardless of zip code. Our public schools are the backbone of our communities.\n\nThank you for standing with students and educators.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to fully fund public education and support teachers. Please invest in our public schools. Thank you.",
    },
    {
        "title": "Housing affordability",
        "issue_slug": "housing",
        "subject": "Support affordable housing and tenant protections",
        "body": "Support affordable housing, rental assistance, and tenant protections.",
        "email_body": "I am a constituent writing to ask you to support affordable housing and tenant protections. Please back robust funding for housing assistance, eviction prevention, and building more affordable units. No one should be homeless or housing-insecure in a country as wealthy as ours. Congress must act.\n\nThank you for your attention to this crisis.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support affordable housing and tenant protections. Please fund housing assistance and eviction prevention. Thank you.",
    },
    {
        "title": "Childcare and pre-K",
        "issue_slug": "childcare",
        "subject": "Support affordable childcare and universal pre-K",
        "body": "Support affordable, high-quality childcare and universal pre-K.",
        "email_body": "I am a constituent writing to ask you to support affordable childcare and universal pre-K. Families are paying a fortune for care while early educators are underpaid. Please back federal investment so every family can afford quality care and every child has a strong start. This is essential infrastructure for our economy and our future.\n\nThank you for fighting for families and kids.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support affordable childcare and universal pre-K. Please invest in early care and education. Thank you.",
    },
    {
        "title": "Paid family leave",
        "issue_slug": "paid-leave",
        "subject": "Support paid family and medical leave",
        "body": "Support national paid family and medical leave so no one has to choose between job and family.",
        "email_body": "I am a constituent writing to ask you to support paid family and medical leave for all workers. No one should have to choose between a paycheck and caring for a new baby or a sick relative. The United States is one of the only wealthy countries without this—please help pass a federal paid leave program.\n\nThank you for standing with working families.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support paid family and medical leave. Please back a federal paid leave program. Thank you.",
    },
    {
        "title": "Raise the minimum wage",
        "issue_slug": "minimum-wage",
        "subject": "Raise the federal minimum wage to a living wage",
        "body": "Support raising the federal minimum wage so full-time work pays enough to live on.",
        "email_body": "I am a constituent writing to ask you to raise the federal minimum wage to a living wage. No one who works full-time should live in poverty. Please support at least $15 an hour and indexing it to inflation. It's past time for Congress to stand with low-wage workers.\n\nThank you for considering this.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to raise the federal minimum wage to a living wage. Please support at least $15 an hour. Thank you.",
    },
    {
        "title": "Overturn Schedule F — protect federal workers and civil service",
        "issue_slug": "unions",
        "subject": "Overturn the rule that strips 50,000 federal workers of job protections",
        "body": "A February 2026 rule reclassifies 50,000 federal workers as at-will, stripping civil service protections. Support the CRA or legislation to overturn it.",
        "email_body": "I am a constituent writing to ask you to overturn the Schedule Policy/Career rule finalized in early February 2026. This rule strips approximately 50,000 federal workers of civil service protections, making them at-will employees who can be fired for political reasons rather than merit. It takes effect March 8. Ninety-four percent of public comments opposed it.\n\nPlease use the Congressional Review Act or support legislation to block this rule. Civil service independence protects our democracy—Congress must act. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to overturn the rule that strips 50,000 federal workers of job protections. Please support the CRA or legislation to block it. Thank you.",
    },
    {
        "title": "Infrastructure",
        "issue_slug": "infrastructure",
        "subject": "Invest in infrastructure and create good jobs",
        "body": "Support robust federal investment in roads, transit, water, and broadband.",
        "email_body": "I am a constituent writing to ask you to support robust federal investment in infrastructure—roads, bridges, transit, clean water, and broadband. These investments create good jobs and strengthen our economy. Please fund projects that prioritize communities that have been left behind and create union jobs.\n\nThank you for building a better America.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support strong infrastructure investment—roads, transit, water, broadband. Please fund projects that create good jobs. Thank you.",
    },
    {
        "title": "Protect and expand Medicare drug negotiation",
        "issue_slug": "drug-pricing",
        "subject": "Protect Medicare drug negotiation — extend lower prices to everyone",
        "body": "Medicare negotiated prices for 10 drugs took effect Jan 2026. Protect this program and extend negotiated prices to all Americans.",
        "email_body": "I am a constituent writing to ask you to protect and expand Medicare's drug price negotiation program. Negotiated prices for 10 high-cost drugs took effect in January 2026, saving beneficiaries billions. Please oppose any effort to weaken this program and support legislation to extend Medicare-negotiated prices to all Americans—not just Medicare enrollees. No one should skip medications or go into debt because of pharmaceutical company greed.\n\nThank you for fighting for affordable medicines.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect Medicare drug negotiation and extend negotiated prices to everyone. Thank you.",
    },
    {
        "title": "Protect Medicare and Social Security",
        "issue_slug": "medicare-social-security",
        "subject": "Protect Medicare and Social Security from cuts",
        "body": "Oppose cuts to Medicare and Social Security; strengthen both programs.",
        "email_body": "I am a constituent writing to ask you to protect Medicare and Social Security from any cuts. These programs are lifelines for seniors and people with disabilities. Please oppose raising the retirement age or reducing benefits, and support expanding Social Security. Americans have earned these benefits through a lifetime of work.\n\nThank you for defending our earned benefits.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect Medicare and Social Security from cuts. Please oppose any benefit reductions. Thank you.",
    },
    {
        "title": "Pass the Equality Act — attacks on LGBTQ+ rights are escalating",
        "issue_slug": "lgbtq-rights",
        "subject": "Pass the Equality Act — state attacks on LGBTQ+ people are escalating",
        "body": "Over 22 states enacted anti-LGBTQ policies in 2025; bathroom bills and more are advancing in 2026. Pass the Equality Act now.",
        "email_body": "I am a constituent writing to urge you to pass the Equality Act (H.R. 15). Attacks on LGBTQ+ rights are escalating—over 22 states enacted anti-LGBTQ policies in 2025, and 2026 has seen bathroom bills and other discriminatory measures advance. The Equality Act would establish federal protections in employment, housing, healthcare, and public life. Everyone deserves to live with dignity and without fear.\n\nPlease pass the Equality Act and stand on the right side of history. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to pass the Equality Act. State attacks on LGBTQ+ people are escalating—we need federal protections now. Thank you.",
    },
    {
        "title": "Racial justice and equity",
        "issue_slug": "racial-justice",
        "subject": "Advance racial justice and equity",
        "body": "Support policies that advance racial justice and address systemic inequality.",
        "email_body": "I am a constituent writing to ask you to advance racial justice and equity. Please support policies that address systemic inequality in housing, education, healthcare, and the economy—and that confront our history of discrimination. Silence is complicity. I'm counting on you to use your position to push for real change.\n\nThank you for listening.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support racial justice and policies that address systemic inequality. Thank you.",
    },
    {
        "title": "Criminal justice reform",
        "issue_slug": "criminal-justice",
        "subject": "Support criminal justice reform and second chances",
        "body": "Support sentencing reform, reentry programs, and ending mass incarceration.",
        "email_body": "I am a constituent writing to ask you to support criminal justice reform. Please back sentencing reform, reentry programs, and policies that reduce mass incarceration while keeping communities safe. Our system is broken and disproportionately harms people of color. Congress can help fix it.\n\nThank you for supporting second chances and a fairer system.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support criminal justice reform—sentencing reform, reentry, and reducing mass incarceration. Thank you.",
    },
    {
        "title": "Policing accountability",
        "issue_slug": "policing",
        "subject": "Support police accountability and community safety",
        "body": "Support accountability, transparency, and reforms that keep communities safe.",
        "email_body": "I am a constituent writing to ask you to support police accountability and transparency. Please back reforms that hold law enforcement to high standards, end qualified immunity where it blocks justice, and invest in community-based safety. We can support both accountability and safety—they go together.\n\nThank you for taking this seriously.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support police accountability and reforms that ensure transparency and justice. Thank you.",
    },
    {
        "title": "Supreme Court and judiciary",
        "issue_slug": "supreme-court",
        "subject": "Support Supreme Court and judicial reform",
        "body": "Support ethics reform and balance on the Supreme Court and federal judiciary.",
        "email_body": "I am a constituent writing to ask you to support Supreme Court and judicial reform. Please back ethics rules for the Court, and consider structural reforms so the judiciary reflects our democracy rather than partisan capture. The courts should protect rights and rule of law—we need Congress to act to restore confidence.\n\nThank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support Supreme Court ethics reform and judicial accountability. Thank you.",
    },
    {
        "title": "Democracy reform",
        "issue_slug": "democracy-reform",
        "subject": "Strengthen democracy and protect elections",
        "body": "Support reforms that strengthen democracy and protect free and fair elections.",
        "email_body": "I am a constituent writing to ask you to strengthen our democracy. Please support reforms that protect free and fair elections, ensure peaceful transitions of power, and hold bad actors accountable. Our democracy is fragile—Congress must defend it. I'm counting on you.\n\nThank you for standing up for democracy.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support democracy reform and protect free and fair elections. Thank you.",
    },
    {
        "title": "End gerrymandering",
        "issue_slug": "gerrymandering",
        "subject": "Support fair maps and end partisan gerrymandering",
        "body": "Support independent redistricting and fair maps so voters choose representatives, not the other way around.",
        "email_body": "I am a constituent writing to ask you to support an end to partisan gerrymandering. Please back federal standards for fair redistricting so that voters choose their representatives—not the other way around. Fair maps are essential for a functioning democracy.\n\nThank you for fighting for fair representation.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support fair redistricting and an end to gerrymandering. Thank you.",
    },
    {
        "title": "Campaign finance reform",
        "issue_slug": "campaign-finance",
        "subject": "Get big money out of politics",
        "body": "Support campaign finance reform and reducing the influence of big money in politics.",
        "email_body": "I am a constituent writing to ask you to support campaign finance reform and get big money out of politics. Please back disclosure, limits, and public financing so that ordinary voters—not just wealthy donors—have a say. Our democracy should not be for sale.\n\nThank you for standing up for clean elections.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support campaign finance reform and get big money out of politics. Thank you.",
    },
    {
        "title": "Ukraine and NATO",
        "issue_slug": "ukraine-nato",
        "subject": "Support Ukraine and strengthen NATO",
        "body": "Support continued aid to Ukraine and strengthening NATO and democratic allies.",
        "email_body": "I am a constituent writing to ask you to support Ukraine in its fight against Russian aggression and to strengthen NATO and our democratic allies. Please back continued humanitarian and military assistance to Ukraine and investments in our alliances. Authoritarianism must not prevail.\n\nThank you for standing with democracy abroad.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support Ukraine and strengthen NATO. Please back continued aid to Ukraine. Thank you.",
    },
    {
        "title": "China policy",
        "issue_slug": "china",
        "subject": "Support a strong, principled approach to China",
        "body": "Support human rights, fair trade, and standing up to aggression while avoiding unnecessary conflict.",
        "email_body": "I am a constituent writing to ask you to support a strong, principled approach to China—one that stands up for human rights, fair trade, and our allies, while avoiding reckless confrontation. Please balance competition with diplomacy and put American workers and values first.\n\nThank you for your judgment on this critical relationship.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support a principled China policy—human rights, fair trade, and smart diplomacy. Thank you.",
    },
    {
        "title": "Border security and asylum",
        "issue_slug": "border-asylum",
        "subject": "Humane border policy and fair asylum process",
        "body": "Support secure borders and a fair, humane asylum process.",
        "email_body": "I am a constituent writing to ask you to support border policies that are both secure and humane. Please fund a fair and efficient asylum process, support personnel and technology where they help, and reject cruelty toward families and children. We can have order and compassion.\n\nThank you for working toward solutions.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support humane border policy and a fair asylum process. Thank you.",
    },
    {
        "title": "DACA and Dreamers",
        "issue_slug": "daca",
        "subject": "Protect Dreamers and create a path to citizenship",
        "body": "Protect DACA recipients and create a permanent path to citizenship for Dreamers.",
        "email_body": "I am a constituent writing to ask you to protect Dreamers and create a permanent path to citizenship. These are our neighbors, classmates, and coworkers—they deserve certainty and a chance to fully participate in the country they call home. Please pass legislation that gives Dreamers the security they deserve.\n\nThank you for standing with Dreamers.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect Dreamers and create a path to citizenship. Please pass a permanent solution. Thank you.",
    },
    {
        "title": "Tax fairness",
        "issue_slug": "tax-fairness",
        "subject": "Support tax fairness—make the wealthy and corporations pay their share",
        "body": "Support tax policies that ask the wealthy and corporations to pay their fair share.",
        "email_body": "I am a constituent writing to ask you to support tax fairness. Please ensure the wealthy and large corporations pay their fair share and close loopholes that let them avoid taxes. Revenue from a fair tax system should fund healthcare, education, and infrastructure that help working families. No more free rides for the top.\n\nThank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support tax fairness—make the wealthy and corporations pay their fair share. Thank you.",
    },
    {
        "title": "Deficit and debt ceiling",
        "issue_slug": "deficit-debt",
        "subject": "Responsible fiscal policy—no hostage-taking over the debt ceiling",
        "body": "Oppose using the debt ceiling as a weapon; support responsible fiscal policy.",
        "email_body": "I am a constituent writing to ask you to oppose using the debt ceiling as a political weapon. Please avoid default and support responsible fiscal policy that doesn't punish working families or cut essential programs. The full faith and credit of the United States must not be gambled for partisan gain.\n\nThank you for acting responsibly.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to oppose debt ceiling hostage-taking and support responsible fiscal policy. Thank you.",
    },
    {
        "title": "Opioid crisis",
        "issue_slug": "opioid",
        "subject": "Support addiction treatment and harm reduction",
        "body": "Support funding for treatment, harm reduction, and addressing the opioid crisis.",
        "email_body": "I am a constituent writing to ask you to support a comprehensive response to the opioid crisis. Please fund treatment, harm reduction, and recovery services—and treat addiction as the health crisis it is, not a crime. Too many families have been devastated. Congress must step up.\n\nThank you for supporting those affected by this crisis.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support addiction treatment and harm reduction funding. Thank you.",
    },
    {
        "title": "Mental health and addiction",
        "issue_slug": "mental-health",
        "subject": "Invest in mental health and addiction services",
        "body": "Support robust funding for mental health and addiction care.",
        "email_body": "I am a constituent writing to ask you to invest in mental health and addiction services. Please fund crisis care, community-based services, and parity so mental health is treated like other health. Too many people cannot get the help they need. This is a matter of lives and families.\n\nThank you for prioritizing mental health.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support mental health and addiction funding and parity. Thank you.",
    },
    {
        "title": "Veterans' benefits",
        "issue_slug": "veterans",
        "subject": "Fully fund veterans' healthcare and benefits",
        "body": "Support full funding for VA healthcare, benefits, and veteran support services.",
        "email_body": "I am a constituent writing to ask you to fully fund veterans' healthcare and benefits. Please support the VA, disability benefits, and programs that help veterans transition to civilian life. Those who served our country deserve the best care and support we can provide. Honor their sacrifice with action.\n\nThank you for supporting our veterans.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to fully fund veterans' healthcare and benefits. Please support the VA and our veterans. Thank you.",
    },
    {
        "title": "Broadband and rural access",
        "issue_slug": "broadband",
        "subject": "Expand affordable broadband to every community",
        "body": "Support affordable high-speed internet for rural and underserved areas.",
        "email_body": "I am a constituent writing to ask you to expand affordable broadband to every community. Please support funding that brings high-speed internet to rural and underserved areas so that families, students, and businesses aren't left behind. Internet access is essential infrastructure in the 21st century.\n\nThank you for closing the digital divide.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support affordable broadband for rural and underserved areas. Thank you.",
    },
    {
        "title": "Clean energy and jobs",
        "issue_slug": "clean-energy",
        "subject": "Support clean energy jobs and restore vehicle emission standards",
        "body": "EPA rescinded vehicle GHG standards in Feb 2026. Support clean energy investment and restoring emission standards for EVs and clean transport.",
        "email_body": "I am a constituent writing to ask you to support clean energy jobs and restore vehicle emission standards. The EPA's February 2026 rescission of motor vehicle GHG standards undermines the transition to electric vehicles and clean transport—Congress must act to restore those standards and invest in renewables, grid modernization, and job training. The shift to a clean economy should create good jobs and not leave anyone behind.\n\nThank you for building a clean energy economy.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support clean energy investment and restore vehicle emission standards that the EPA recently repealed. Thank you.",
    },
    {
        "title": "Environmental protection",
        "issue_slug": "environment",
        "subject": "Protect our air, water, and public lands — restore EPA authority",
        "body": "EPA rescinded the GHG endangerment finding in Feb 2026. Support strong environmental standards and restore EPA authority to regulate greenhouse gases.",
        "email_body": "I am a constituent writing to ask you to protect our air, water, and public lands. The EPA's February 2026 rescission of the greenhouse gas endangerment finding is a devastating example of weakened protections—Congress must restore EPA authority to regulate GHG emissions. Please support strong environmental standards, conservation funding, and holding polluters accountable. We have one planet—Congress must safeguard it for future generations.\n\nThank you for standing up for our environment.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect our air, water, and public lands and to restore EPA authority to regulate greenhouse gases after the recent rescission. Thank you.",
    },
    {
        "title": "Women's rights and equal pay",
        "issue_slug": "womens-rights",
        "subject": "Support women's rights and equal pay",
        "body": "Support equal pay, reproductive rights, and policies that advance gender equity.",
        "email_body": "I am a constituent writing to ask you to support women's rights and equal pay. Please back the Equal Rights Amendment, pay equity legislation, and reproductive freedom. Women deserve equal treatment in the workplace and control over their own bodies. Congress should be leading, not lagging.\n\nThank you for standing with women.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support equal pay and women's rights. Thank you.",
    },
    {
        "title": "Disability rights",
        "issue_slug": "disability-rights",
        "subject": "Protect and expand disability rights",
        "body": "Support the ADA, accessibility, and inclusion for people with disabilities.",
        "email_body": "I am a constituent writing to ask you to protect and expand disability rights. Please support the ADA, full funding for inclusion and accessibility, and policies that ensure people with disabilities can live independently and participate fully. Don't roll back the progress we've made.\n\nThank you for standing with the disability community.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect disability rights and support accessibility and inclusion. Thank you.",
    },
    {
        "title": "Elder care and aging",
        "issue_slug": "elder-care",
        "subject": "Support seniors and elder care",
        "body": "Support funding for senior services, elder care, and aging with dignity.",
        "email_body": "I am a constituent writing to ask you to support seniors and elder care. Please fund programs that help older Americans age with dignity—including home and community-based services, caregiver support, and strong Medicare and Social Security. Our parents and grandparents deserve security and care.\n\nThank you for standing with seniors.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support elder care and aging services. Thank you.",
    },
    {
        "title": "Food security and SNAP",
        "issue_slug": "snap",
        "subject": "Protect SNAP and fight hunger",
        "body": "Protect and strengthen SNAP and federal nutrition programs.",
        "email_body": "I am a constituent writing to ask you to protect and strengthen SNAP and federal nutrition programs. No one in America should go hungry. Please oppose any cuts to food assistance and support expanding access so families, children, and seniors have enough to eat. Fighting hunger is a moral imperative.\n\nThank you for protecting SNAP.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect SNAP and fight hunger. Please oppose cuts to food assistance. Thank you.",
    },
    {
        "title": "Oppose $1 trillion in proposed Medicaid cuts",
        "issue_slug": "medicaid",
        "subject": "Oppose Republican budget's $1 trillion in Medicaid cuts",
        "body": "Republicans have proposed $1 trillion in Medicaid cuts in their budget framework. Oppose these cuts and protect healthcare for vulnerable Americans.",
        "email_body": "I am a constituent writing to urge you to oppose the proposed $1 trillion in Medicaid cuts in the Republican budget framework. Medicaid is a lifeline for low-income families, children, people with disabilities, and seniors in nursing care. These cuts would devastate access to healthcare for millions of Americans.\n\nPlease oppose any cuts or block-grant schemes and support protecting and expanding Medicaid. Congress must stand with vulnerable Americans, not strip away their healthcare. Thank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to oppose the proposed $1 trillion in Medicaid cuts. Please protect Medicaid. Thank you.",
    },
    {
        "title": "Restore ACA premium tax credits — they expired in 2025",
        "issue_slug": "aca",
        "subject": "Extend the enhanced ACA premium tax credits — premiums are up 75% without them",
        "body": "Enhanced ACA subsidies expired Dec 2025. Net premiums rose over 75% for many. Support extending the premium tax credits.",
        "email_body": "I am a constituent writing to ask you to extend the enhanced ACA premium tax credits that expired at the end of 2025. Without them, many Marketplace enrollees have seen net premiums rise over 75%, and healthier people are dropping coverage—hurting everyone. Please support legislation to restore these credits so families can afford health insurance. Protect the ACA and pre-existing condition protections.\n\nThank you for protecting our care.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to extend the ACA premium tax credits that expired. Please support legislation to restore affordable Marketplace coverage. Thank you.",
    },
    {
        "title": "Trade and manufacturing",
        "issue_slug": "trade",
        "subject": "Support fair trade and American manufacturing",
        "body": "Support fair trade deals and policies that strengthen American manufacturing and workers.",
        "email_body": "I am a constituent writing to ask you to support fair trade and American manufacturing. Please back trade policies that protect workers and the environment, invest in domestic manufacturing, and ensure that globalization doesn't leave working people behind. We need trade that works for everyone.\n\nThank you.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support fair trade and American manufacturing. Thank you.",
    },
    {
        "title": "Small business support",
        "issue_slug": "small-business",
        "subject": "Support small businesses and main street",
        "body": "Support access to capital, fair competition, and policies that help small businesses thrive.",
        "email_body": "I am a constituent writing to ask you to support small businesses and main street. Please back access to capital, fair competition with large corporations, and policies that help local businesses thrive. Small businesses are the backbone of our communities—they deserve a level playing field.\n\nThank you for supporting small business.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support small businesses and main street. Thank you.",
    },
    {
        "title": "Support family farms in the 2026 Farm Bill",
        "issue_slug": "agriculture",
        "subject": "Support family farmers, conservation, and rural communities in the Farm Bill",
        "body": "The House introduced the Farm, Food, and National Security Act of 2026 on Feb 13. Support family farmers, conservation, and rural infrastructure.",
        "email_body": "I am a constituent writing to ask you to support family farms and sustainable agriculture in the 2026 Farm Bill. The House Agriculture Committee introduced the Farm, Food, and National Security Act on February 13. Please back programs that help family farmers, promote conservation and climate-smart practices, strengthen rural childcare and broadband, and protect our food supply. Rural America deserves good policy.\n\nThank you for standing with farmers.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support family farms, conservation, and rural communities in the 2026 Farm Bill. Thank you.",
    },
    {
        "title": "Tribal sovereignty and Native issues",
        "issue_slug": "tribal",
        "subject": "Honor tribal sovereignty and support Native communities",
        "body": "Support tribal sovereignty, treaty obligations, and investments in Native communities.",
        "email_body": "I am a constituent writing to ask you to honor tribal sovereignty and support Native communities. Please uphold treaty obligations, fund Indian Country programs adequately, and respect tribal self-determination. Native nations and Indigenous people deserve justice and investment—Congress must do its part.\n\nThank you for standing with Native communities.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support tribal sovereignty and Native communities. Thank you.",
    },
    {
        "title": "Postal service and voting by mail",
        "issue_slug": "postal-voting",
        "subject": "Protect the Postal Service and voting by mail",
        "body": "Support a strong USPS and accessible vote-by-mail options.",
        "email_body": "I am a constituent writing to ask you to protect the Postal Service and voting by mail. The USPS is a vital public service—please oppose cuts and support full funding. And please protect vote-by-mail and drop boxes so every American can vote safely and conveniently. Democracy depends on it.\n\nThank you for supporting the USPS and voting access.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to protect the Postal Service and voting by mail. Thank you.",
    },
    {
        "title": "Net neutrality and tech regulation",
        "issue_slug": "net-neutrality",
        "subject": "Restore net neutrality and support tech accountability",
        "body": "Support net neutrality and sensible tech regulation to protect consumers and democracy.",
        "email_body": "I am a constituent writing to ask you to restore net neutrality and support tech accountability. Please ensure the internet remains open and that large platforms are held accountable for privacy, competition, and disinformation. Technology should serve the public interest.\n\nThank you for standing up for consumers and democracy online.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support net neutrality and tech accountability. Thank you.",
    },
    {
        "title": "Other or specific bill",
        "issue_slug": "other",
        "subject": "Constituent request",
        "body": "Use this for a topic or bill not listed—customize the message.",
        "email_body": "I am a constituent writing to ask you to support [describe the issue or bill]. This matters to me and my community. I'm counting on you to listen to your constituents and do the right thing.\n\nThank you for your time and your service.",
        "call_script": "Hi, I'm a constituent from [your city or state]. I'm calling to ask you to support [describe the issue or bill]. Thank you for your time.",
    },
]
