"""
Curated script library: 50 top American political topics with full email and call scripts.
Progressive, topic-specific, constituent pressure on Congress. Used when Gemini is not available or for demo.
"""
# Each entry: title, issue_slug, subject, body (short summary), email_body (full), call_script (full)

SCRIPT_LIBRARY = [
    {
        "title": "Support climate action",
        "issue_slug": "climate",
        "subject": "Support bold climate legislation",
        "body": "Urge strong climate legislation and clean energy investments.",
        "email_body": "I am a constituent writing to urge you to support bold climate legislation and treat the climate crisis as the emergency it is. Please push for ambitious emissions reductions, investments in clean energy and green jobs, and environmental justice for communities most affected. We need Congress to act now—future generations are counting on you.\n\nThank you for your service. I will be paying attention to how you vote on climate.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support strong climate legislation and clean energy investments. Please vote for bold emissions cuts and green jobs. Thank you for your time.",
    },
    {
        "title": "Protect voting rights",
        "issue_slug": "voting-rights",
        "subject": "Protect voting rights and oppose restrictions",
        "body": "Protect voting rights and oppose legislation that makes it harder to vote.",
        "email_body": "I am a constituent and I'm writing to ask you to protect voting rights and oppose any legislation that makes it harder for Americans to vote. Support federal standards that ensure access to the ballot, restore the Voting Rights Act, and reject voter suppression. Democracy only works when every voice can be heard.\n\nPlease stand up for the right to vote. Thank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect voting rights and oppose any laws that restrict access to the ballot. Please support federal voting standards. Thank you.",
    },
    {
        "title": "Support affordable healthcare",
        "issue_slug": "healthcare",
        "subject": "Support affordable healthcare and lower drug costs",
        "body": "Support affordable healthcare, lower prescription drug costs, and protect the ACA.",
        "email_body": "I am a constituent writing to ask you to support affordable healthcare and lower prescription drug costs. Please protect and strengthen the Affordable Care Act, allow Medicare to negotiate drug prices, and expand access so no one has to choose between health and financial ruin. Healthcare is a right.\n\nI'm counting on you to stand up to pharmaceutical and insurance interests. Thank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support affordable healthcare and lower prescription drug costs. Please protect the ACA and back Medicare negotiation. Thank you.",
    },
    {
        "title": "Protect abortion access",
        "issue_slug": "abortion",
        "subject": "Protect abortion access and reproductive freedom",
        "body": "Protect abortion access and reproductive freedom for everyone.",
        "email_body": "I am a constituent writing to urge you to protect abortion access and reproductive freedom. Please support federal legislation that codifies the right to choose and ensures everyone can access reproductive healthcare regardless of where they live. Politicians should not control our bodies or our decisions.\n\nStand with the majority of Americans who support reproductive rights. Thank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect abortion access and reproductive freedom. Please support federal legislation that codifies the right to choose. Thank you.",
    },
    {
        "title": "Gun violence prevention",
        "issue_slug": "gun-violence",
        "subject": "Support gun violence prevention and safer communities",
        "body": "Support common-sense gun safety laws to save lives.",
        "email_body": "I am a constituent writing to ask you to support gun violence prevention and common-sense gun safety laws. Please back universal background checks, red-flag laws, and closing loopholes that put weapons in the wrong hands. Our communities deserve to be safe—thoughts and prayers are not enough.\n\nI urge you to vote for legislation that will save lives. Thank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support gun violence prevention—background checks, red-flag laws, and closing loopholes. Please vote for gun safety. Thank you.",
    },
    {
        "title": "Immigration reform",
        "issue_slug": "immigration",
        "subject": "Support humane immigration reform and a path to citizenship",
        "body": "Support humane immigration reform and a path to citizenship.",
        "email_body": "I am a constituent writing to ask you to support humane immigration reform and a path to citizenship for undocumented immigrants who contribute to our communities. Please oppose cruel enforcement-only approaches and support protecting Dreamers, reuniting families, and treating immigrants with dignity. Our country is stronger when we welcome those who seek a better life.\n\nThank you for considering my views.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support immigration reform and a path to citizenship. Please protect Dreamers and support humane policies. Thank you.",
    },
    {
        "title": "Economy and jobs",
        "issue_slug": "economy-jobs",
        "subject": "Support working families and good jobs",
        "body": "Support policies that create good jobs and strengthen working families.",
        "email_body": "I am a constituent writing to ask you to support policies that create good jobs and strengthen working families. Please back investments in infrastructure, manufacturing, and green jobs; strengthen labor rights; and ensure workers share in economic growth. Too many families are one paycheck away from crisis—Congress should be on their side.\n\nThank you for fighting for working people.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support good jobs and working families—infrastructure, labor rights, and shared prosperity. Thank you.",
    },
    {
        "title": "Inflation and cost of living",
        "issue_slug": "inflation",
        "subject": "Lower costs for families and crack down on price gouging",
        "body": "Support lowering costs and holding corporations accountable for price gouging.",
        "email_body": "I am a constituent writing to ask you to address the cost of living and stand up to corporate price gouging. Please support policies that lower costs for housing, healthcare, and essentials—and hold companies accountable when they raise prices unfairly. Working families need relief, not more giveaways to big corporations.\n\nThank you for listening.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to lower costs for families and crack down on price gouging. Please support real relief for working people. Thank you.",
    },
    {
        "title": "Student debt relief",
        "issue_slug": "student-debt",
        "subject": "Support student debt relief and affordable college",
        "body": "Support student debt cancellation and affordable higher education.",
        "email_body": "I am a constituent writing to ask you to support student debt relief and affordable higher education. Please back cancellation of federal student debt and policies that make college and trade school accessible without a lifetime of debt. Education should open doors, not bury people in loans.\n\nI urge you to stand with students and borrowers. Thank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support student debt relief and affordable college. Please back debt cancellation and accessible education. Thank you.",
    },
    {
        "title": "Public education funding",
        "issue_slug": "education",
        "subject": "Fully fund public education and support teachers",
        "body": "Support full funding for public schools and respect for educators.",
        "email_body": "I am a constituent writing to ask you to fully fund public education and support teachers and staff. Please oppose vouchers that drain resources from public schools and support federal investment in K–12 so every child has a great education regardless of zip code. Our public schools are the backbone of our communities.\n\nThank you for standing with students and educators.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to fully fund public education and support teachers. Please invest in our public schools. Thank you.",
    },
    {
        "title": "Housing affordability",
        "issue_slug": "housing",
        "subject": "Support affordable housing and tenant protections",
        "body": "Support affordable housing, rental assistance, and tenant protections.",
        "email_body": "I am a constituent writing to ask you to support affordable housing and tenant protections. Please back robust funding for housing assistance, eviction prevention, and building more affordable units. No one should be homeless or housing-insecure in a country as wealthy as ours. Congress must act.\n\nThank you for your attention to this crisis.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support affordable housing and tenant protections. Please fund housing assistance and eviction prevention. Thank you.",
    },
    {
        "title": "Childcare and pre-K",
        "issue_slug": "childcare",
        "subject": "Support affordable childcare and universal pre-K",
        "body": "Support affordable, high-quality childcare and universal pre-K.",
        "email_body": "I am a constituent writing to ask you to support affordable childcare and universal pre-K. Families are paying a fortune for care while early educators are underpaid. Please back federal investment so every family can afford quality care and every child has a strong start. This is essential infrastructure for our economy and our future.\n\nThank you for fighting for families and kids.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support affordable childcare and universal pre-K. Please invest in early care and education. Thank you.",
    },
    {
        "title": "Paid family leave",
        "issue_slug": "paid-leave",
        "subject": "Support paid family and medical leave",
        "body": "Support national paid family and medical leave so no one has to choose between job and family.",
        "email_body": "I am a constituent writing to ask you to support paid family and medical leave for all workers. No one should have to choose between a paycheck and caring for a new baby or a sick relative. The United States is one of the only wealthy countries without this—please help pass a federal paid leave program.\n\nThank you for standing with working families.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support paid family and medical leave. Please back a federal paid leave program. Thank you.",
    },
    {
        "title": "Raise the minimum wage",
        "issue_slug": "minimum-wage",
        "subject": "Raise the federal minimum wage to a living wage",
        "body": "Support raising the federal minimum wage so full-time work pays enough to live on.",
        "email_body": "I am a constituent writing to ask you to raise the federal minimum wage to a living wage. No one who works full-time should live in poverty. Please support at least $15 an hour and indexing it to inflation. It's past time for Congress to stand with low-wage workers.\n\nThank you for considering this.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to raise the federal minimum wage to a living wage. Please support at least $15 an hour. Thank you.",
    },
    {
        "title": "Workers' rights and unions",
        "issue_slug": "unions",
        "subject": "Protect the right to organize and support unions",
        "body": "Protect the right to unionize and support workers organizing for better pay and conditions.",
        "email_body": "I am a constituent writing to ask you to protect the right to organize and support unions. Please back the PRO Act and oppose anti-union legislation. When workers can bargain collectively, everyone benefits—better wages, safer workplaces, and a stronger middle class. Stand with workers, not only with corporations.\n\nThank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect the right to unionize. Please support the PRO Act and workers organizing. Thank you.",
    },
    {
        "title": "Infrastructure",
        "issue_slug": "infrastructure",
        "subject": "Invest in infrastructure and create good jobs",
        "body": "Support robust federal investment in roads, transit, water, and broadband.",
        "email_body": "I am a constituent writing to ask you to support robust federal investment in infrastructure—roads, bridges, transit, clean water, and broadband. These investments create good jobs and strengthen our economy. Please fund projects that prioritize communities that have been left behind and create union jobs.\n\nThank you for building a better America.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support strong infrastructure investment—roads, transit, water, broadband. Please fund projects that create good jobs. Thank you.",
    },
    {
        "title": "Prescription drug pricing",
        "issue_slug": "drug-pricing",
        "subject": "Lower prescription drug prices and allow Medicare to negotiate",
        "body": "Support Medicare negotiation and lower drug prices for everyone.",
        "email_body": "I am a constituent writing to ask you to lower prescription drug prices. Please allow Medicare to negotiate drug prices and extend those lower prices to everyone. No one should skip medications or go into debt because of pharmaceutical company greed. Congress must stand up to Big Pharma.\n\nThank you for fighting for affordable medicines.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support Medicare negotiation and lower drug prices. Please stand up to pharmaceutical companies. Thank you.",
    },
    {
        "title": "Protect Medicare and Social Security",
        "issue_slug": "medicare-social-security",
        "subject": "Protect Medicare and Social Security from cuts",
        "body": "Oppose cuts to Medicare and Social Security; strengthen both programs.",
        "email_body": "I am a constituent writing to ask you to protect Medicare and Social Security from any cuts. These programs are lifelines for seniors and people with disabilities. Please oppose raising the retirement age or reducing benefits, and support expanding Social Security. Americans have earned these benefits through a lifetime of work.\n\nThank you for defending our earned benefits.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect Medicare and Social Security from cuts. Please oppose any benefit reductions. Thank you.",
    },
    {
        "title": "LGBTQ+ rights",
        "issue_slug": "lgbtq-rights",
        "subject": "Support LGBTQ+ equality and oppose discrimination",
        "body": "Support the Equality Act and protect LGBTQ+ people from discrimination.",
        "email_body": "I am a constituent writing to ask you to support LGBTQ+ equality and oppose discrimination. Please pass the Equality Act and protect the rights of LGBTQ+ people in employment, housing, healthcare, and public life. Everyone deserves to live with dignity and without fear. Stand on the right side of history.\n\nThank you for your support.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support LGBTQ+ equality and pass the Equality Act. Please protect LGBTQ+ people from discrimination. Thank you.",
    },
    {
        "title": "Racial justice and equity",
        "issue_slug": "racial-justice",
        "subject": "Advance racial justice and equity",
        "body": "Support policies that advance racial justice and address systemic inequality.",
        "email_body": "I am a constituent writing to ask you to advance racial justice and equity. Please support policies that address systemic inequality in housing, education, healthcare, and the economy—and that confront our history of discrimination. Silence is complicity. I'm counting on you to use your position to push for real change.\n\nThank you for listening.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support racial justice and policies that address systemic inequality. Thank you.",
    },
    {
        "title": "Criminal justice reform",
        "issue_slug": "criminal-justice",
        "subject": "Support criminal justice reform and second chances",
        "body": "Support sentencing reform, reentry programs, and ending mass incarceration.",
        "email_body": "I am a constituent writing to ask you to support criminal justice reform. Please back sentencing reform, reentry programs, and policies that reduce mass incarceration while keeping communities safe. Our system is broken and disproportionately harms people of color. Congress can help fix it.\n\nThank you for supporting second chances and a fairer system.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support criminal justice reform—sentencing reform, reentry, and reducing mass incarceration. Thank you.",
    },
    {
        "title": "Policing accountability",
        "issue_slug": "policing",
        "subject": "Support police accountability and community safety",
        "body": "Support accountability, transparency, and reforms that keep communities safe.",
        "email_body": "I am a constituent writing to ask you to support police accountability and transparency. Please back reforms that hold law enforcement to high standards, end qualified immunity where it blocks justice, and invest in community-based safety. We can support both accountability and safety—they go together.\n\nThank you for taking this seriously.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support police accountability and reforms that ensure transparency and justice. Thank you.",
    },
    {
        "title": "Supreme Court and judiciary",
        "issue_slug": "supreme-court",
        "subject": "Support Supreme Court and judicial reform",
        "body": "Support ethics reform and balance on the Supreme Court and federal judiciary.",
        "email_body": "I am a constituent writing to ask you to support Supreme Court and judicial reform. Please back ethics rules for the Court, and consider structural reforms so the judiciary reflects our democracy rather than partisan capture. The courts should protect rights and rule of law—we need Congress to act to restore confidence.\n\nThank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support Supreme Court ethics reform and judicial accountability. Thank you.",
    },
    {
        "title": "Democracy reform",
        "issue_slug": "democracy-reform",
        "subject": "Strengthen democracy and protect elections",
        "body": "Support reforms that strengthen democracy and protect free and fair elections.",
        "email_body": "I am a constituent writing to ask you to strengthen our democracy. Please support reforms that protect free and fair elections, ensure peaceful transitions of power, and hold bad actors accountable. Our democracy is fragile—Congress must defend it. I'm counting on you.\n\nThank you for standing up for democracy.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support democracy reform and protect free and fair elections. Thank you.",
    },
    {
        "title": "End gerrymandering",
        "issue_slug": "gerrymandering",
        "subject": "Support fair maps and end partisan gerrymandering",
        "body": "Support independent redistricting and fair maps so voters choose representatives, not the other way around.",
        "email_body": "I am a constituent writing to ask you to support an end to partisan gerrymandering. Please back federal standards for fair redistricting so that voters choose their representatives—not the other way around. Fair maps are essential for a functioning democracy.\n\nThank you for fighting for fair representation.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support fair redistricting and an end to gerrymandering. Thank you.",
    },
    {
        "title": "Campaign finance reform",
        "issue_slug": "campaign-finance",
        "subject": "Get big money out of politics",
        "body": "Support campaign finance reform and reducing the influence of big money in politics.",
        "email_body": "I am a constituent writing to ask you to support campaign finance reform and get big money out of politics. Please back disclosure, limits, and public financing so that ordinary voters—not just wealthy donors—have a say. Our democracy should not be for sale.\n\nThank you for standing up for clean elections.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support campaign finance reform and get big money out of politics. Thank you.",
    },
    {
        "title": "Ukraine and NATO",
        "issue_slug": "ukraine-nato",
        "subject": "Support Ukraine and strengthen NATO",
        "body": "Support continued aid to Ukraine and strengthening NATO and democratic allies.",
        "email_body": "I am a constituent writing to ask you to support Ukraine in its fight against Russian aggression and to strengthen NATO and our democratic allies. Please back continued humanitarian and military assistance to Ukraine and investments in our alliances. Authoritarianism must not prevail.\n\nThank you for standing with democracy abroad.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support Ukraine and strengthen NATO. Please back continued aid to Ukraine. Thank you.",
    },
    {
        "title": "China policy",
        "issue_slug": "china",
        "subject": "Support a strong, principled approach to China",
        "body": "Support human rights, fair trade, and standing up to aggression while avoiding unnecessary conflict.",
        "email_body": "I am a constituent writing to ask you to support a strong, principled approach to China—one that stands up for human rights, fair trade, and our allies, while avoiding reckless confrontation. Please balance competition with diplomacy and put American workers and values first.\n\nThank you for your judgment on this critical relationship.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support a principled China policy—human rights, fair trade, and smart diplomacy. Thank you.",
    },
    {
        "title": "Border security and asylum",
        "issue_slug": "border-asylum",
        "subject": "Humane border policy and fair asylum process",
        "body": "Support secure borders and a fair, humane asylum process.",
        "email_body": "I am a constituent writing to ask you to support border policies that are both secure and humane. Please fund a fair and efficient asylum process, support personnel and technology where they help, and reject cruelty toward families and children. We can have order and compassion.\n\nThank you for working toward solutions.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support humane border policy and a fair asylum process. Thank you.",
    },
    {
        "title": "DACA and Dreamers",
        "issue_slug": "daca",
        "subject": "Protect Dreamers and create a path to citizenship",
        "body": "Protect DACA recipients and create a permanent path to citizenship for Dreamers.",
        "email_body": "I am a constituent writing to ask you to protect Dreamers and create a permanent path to citizenship. These are our neighbors, classmates, and coworkers—they deserve certainty and a chance to fully participate in the country they call home. Please pass legislation that gives Dreamers the security they deserve.\n\nThank you for standing with Dreamers.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect Dreamers and create a path to citizenship. Please pass a permanent solution. Thank you.",
    },
    {
        "title": "Tax fairness",
        "issue_slug": "tax-fairness",
        "subject": "Support tax fairness—make the wealthy and corporations pay their share",
        "body": "Support tax policies that ask the wealthy and corporations to pay their fair share.",
        "email_body": "I am a constituent writing to ask you to support tax fairness. Please ensure the wealthy and large corporations pay their fair share and close loopholes that let them avoid taxes. Revenue from a fair tax system should fund healthcare, education, and infrastructure that help working families. No more free rides for the top.\n\nThank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support tax fairness—make the wealthy and corporations pay their fair share. Thank you.",
    },
    {
        "title": "Deficit and debt ceiling",
        "issue_slug": "deficit-debt",
        "subject": "Responsible fiscal policy—no hostage-taking over the debt ceiling",
        "body": "Oppose using the debt ceiling as a weapon; support responsible fiscal policy.",
        "email_body": "I am a constituent writing to ask you to oppose using the debt ceiling as a political weapon. Please avoid default and support responsible fiscal policy that doesn't punish working families or cut essential programs. The full faith and credit of the United States must not be gambled for partisan gain.\n\nThank you for acting responsibly.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to oppose debt ceiling hostage-taking and support responsible fiscal policy. Thank you.",
    },
    {
        "title": "Opioid crisis",
        "issue_slug": "opioid",
        "subject": "Support addiction treatment and harm reduction",
        "body": "Support funding for treatment, harm reduction, and addressing the opioid crisis.",
        "email_body": "I am a constituent writing to ask you to support a comprehensive response to the opioid crisis. Please fund treatment, harm reduction, and recovery services—and treat addiction as the health crisis it is, not a crime. Too many families have been devastated. Congress must step up.\n\nThank you for supporting those affected by this crisis.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support addiction treatment and harm reduction funding. Thank you.",
    },
    {
        "title": "Mental health and addiction",
        "issue_slug": "mental-health",
        "subject": "Invest in mental health and addiction services",
        "body": "Support robust funding for mental health and addiction care.",
        "email_body": "I am a constituent writing to ask you to invest in mental health and addiction services. Please fund crisis care, community-based services, and parity so mental health is treated like other health. Too many people cannot get the help they need. This is a matter of lives and families.\n\nThank you for prioritizing mental health.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support mental health and addiction funding and parity. Thank you.",
    },
    {
        "title": "Veterans' benefits",
        "issue_slug": "veterans",
        "subject": "Fully fund veterans' healthcare and benefits",
        "body": "Support full funding for VA healthcare, benefits, and veteran support services.",
        "email_body": "I am a constituent writing to ask you to fully fund veterans' healthcare and benefits. Please support the VA, disability benefits, and programs that help veterans transition to civilian life. Those who served our country deserve the best care and support we can provide. Honor their sacrifice with action.\n\nThank you for supporting our veterans.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to fully fund veterans' healthcare and benefits. Please support the VA and our veterans. Thank you.",
    },
    {
        "title": "Broadband and rural access",
        "issue_slug": "broadband",
        "subject": "Expand affordable broadband to every community",
        "body": "Support affordable high-speed internet for rural and underserved areas.",
        "email_body": "I am a constituent writing to ask you to expand affordable broadband to every community. Please support funding that brings high-speed internet to rural and underserved areas so that families, students, and businesses aren't left behind. Internet access is essential infrastructure in the 21st century.\n\nThank you for closing the digital divide.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support affordable broadband for rural and underserved areas. Thank you.",
    },
    {
        "title": "Clean energy and jobs",
        "issue_slug": "clean-energy",
        "subject": "Support clean energy jobs and a just transition",
        "body": "Support clean energy investment and a just transition for workers and communities.",
        "email_body": "I am a constituent writing to ask you to support clean energy jobs and a just transition for workers and communities. Please back investments in renewables, grid modernization, and job training so that the shift to a clean economy creates good jobs and doesn't leave anyone behind. Our future can be green and fair.\n\nThank you for building a clean energy economy.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support clean energy jobs and a just transition for workers. Thank you.",
    },
    {
        "title": "Environmental protection",
        "issue_slug": "environment",
        "subject": "Protect our air, water, and public lands",
        "body": "Support strong environmental protections and conservation.",
        "email_body": "I am a constituent writing to ask you to protect our air, water, and public lands. Please support strong environmental standards, conservation funding, and holding polluters accountable. We have one planet—Congress must safeguard it for future generations. Don't roll back the protections we rely on.\n\nThank you for standing up for our environment.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect our air, water, and public lands. Please support strong environmental protections. Thank you.",
    },
    {
        "title": "Women's rights and equal pay",
        "issue_slug": "womens-rights",
        "subject": "Support women's rights and equal pay",
        "body": "Support equal pay, reproductive rights, and policies that advance gender equity.",
        "email_body": "I am a constituent writing to ask you to support women's rights and equal pay. Please back the Equal Rights Amendment, pay equity legislation, and reproductive freedom. Women deserve equal treatment in the workplace and control over their own bodies. Congress should be leading, not lagging.\n\nThank you for standing with women.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support equal pay and women's rights. Thank you.",
    },
    {
        "title": "Disability rights",
        "issue_slug": "disability-rights",
        "subject": "Protect and expand disability rights",
        "body": "Support the ADA, accessibility, and inclusion for people with disabilities.",
        "email_body": "I am a constituent writing to ask you to protect and expand disability rights. Please support the ADA, full funding for inclusion and accessibility, and policies that ensure people with disabilities can live independently and participate fully. Don't roll back the progress we've made.\n\nThank you for standing with the disability community.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect disability rights and support accessibility and inclusion. Thank you.",
    },
    {
        "title": "Elder care and aging",
        "issue_slug": "elder-care",
        "subject": "Support seniors and elder care",
        "body": "Support funding for senior services, elder care, and aging with dignity.",
        "email_body": "I am a constituent writing to ask you to support seniors and elder care. Please fund programs that help older Americans age with dignity—including home and community-based services, caregiver support, and strong Medicare and Social Security. Our parents and grandparents deserve security and care.\n\nThank you for standing with seniors.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support elder care and aging services. Thank you.",
    },
    {
        "title": "Food security and SNAP",
        "issue_slug": "snap",
        "subject": "Protect SNAP and fight hunger",
        "body": "Protect and strengthen SNAP and federal nutrition programs.",
        "email_body": "I am a constituent writing to ask you to protect and strengthen SNAP and federal nutrition programs. No one in America should go hungry. Please oppose any cuts to food assistance and support expanding access so families, children, and seniors have enough to eat. Fighting hunger is a moral imperative.\n\nThank you for protecting SNAP.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect SNAP and fight hunger. Please oppose cuts to food assistance. Thank you.",
    },
    {
        "title": "Medicaid expansion",
        "issue_slug": "medicaid",
        "subject": "Protect and expand Medicaid",
        "body": "Protect Medicaid and expand access in every state.",
        "email_body": "I am a constituent writing to ask you to protect and expand Medicaid. Please oppose any cuts or block-grant schemes and support expansion so that low-income families, children, and people with disabilities can get healthcare. Medicaid is a lifeline—Congress must protect it.\n\nThank you for standing with Medicaid beneficiaries.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect and expand Medicaid. Thank you.",
    },
    {
        "title": "ACA and pre-existing conditions",
        "issue_slug": "aca",
        "subject": "Protect the ACA and pre-existing condition protections",
        "body": "Protect the Affordable Care Act and guaranteed coverage for pre-existing conditions.",
        "email_body": "I am a constituent writing to ask you to protect the Affordable Care Act and guaranteed coverage for pre-existing conditions. Please oppose any repeal or sabotage. Millions of Americans rely on the ACA for their health coverage—Congress must defend it and build on it.\n\nThank you for protecting our care.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect the ACA and pre-existing condition protections. Thank you.",
    },
    {
        "title": "Trade and manufacturing",
        "issue_slug": "trade",
        "subject": "Support fair trade and American manufacturing",
        "body": "Support fair trade deals and policies that strengthen American manufacturing and workers.",
        "email_body": "I am a constituent writing to ask you to support fair trade and American manufacturing. Please back trade policies that protect workers and the environment, invest in domestic manufacturing, and ensure that globalization doesn't leave working people behind. We need trade that works for everyone.\n\nThank you.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support fair trade and American manufacturing. Thank you.",
    },
    {
        "title": "Small business support",
        "issue_slug": "small-business",
        "subject": "Support small businesses and main street",
        "body": "Support access to capital, fair competition, and policies that help small businesses thrive.",
        "email_body": "I am a constituent writing to ask you to support small businesses and main street. Please back access to capital, fair competition with large corporations, and policies that help local businesses thrive. Small businesses are the backbone of our communities—they deserve a level playing field.\n\nThank you for supporting small business.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support small businesses and main street. Thank you.",
    },
    {
        "title": "Agriculture and farm policy",
        "issue_slug": "agriculture",
        "subject": "Support family farms and sustainable agriculture",
        "body": "Support family farmers, sustainable agriculture, and rural communities.",
        "email_body": "I am a constituent writing to ask you to support family farms and sustainable agriculture. Please back farm bill programs that help family farmers, promote conservation and climate-smart practices, and strengthen rural communities. Our food supply and rural America depend on good policy.\n\nThank you for standing with farmers.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support family farms and sustainable agriculture. Thank you.",
    },
    {
        "title": "Tribal sovereignty and Native issues",
        "issue_slug": "tribal",
        "subject": "Honor tribal sovereignty and support Native communities",
        "body": "Support tribal sovereignty, treaty obligations, and investments in Native communities.",
        "email_body": "I am a constituent writing to ask you to honor tribal sovereignty and support Native communities. Please uphold treaty obligations, fund Indian Country programs adequately, and respect tribal self-determination. Native nations and Indigenous people deserve justice and investment—Congress must do its part.\n\nThank you for standing with Native communities.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support tribal sovereignty and Native communities. Thank you.",
    },
    {
        "title": "Postal service and voting by mail",
        "issue_slug": "postal-voting",
        "subject": "Protect the Postal Service and voting by mail",
        "body": "Support a strong USPS and accessible vote-by-mail options.",
        "email_body": "I am a constituent writing to ask you to protect the Postal Service and voting by mail. The USPS is a vital public service—please oppose cuts and support full funding. And please protect vote-by-mail and drop boxes so every American can vote safely and conveniently. Democracy depends on it.\n\nThank you for supporting the USPS and voting access.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to protect the Postal Service and voting by mail. Thank you.",
    },
    {
        "title": "Net neutrality and tech regulation",
        "issue_slug": "net-neutrality",
        "subject": "Restore net neutrality and support tech accountability",
        "body": "Support net neutrality and sensible tech regulation to protect consumers and democracy.",
        "email_body": "I am a constituent writing to ask you to restore net neutrality and support tech accountability. Please ensure the internet remains open and that large platforms are held accountable for privacy, competition, and disinformation. Technology should serve the public interest.\n\nThank you for standing up for consumers and democracy online.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support net neutrality and tech accountability. Thank you.",
    },
    {
        "title": "Other or specific bill",
        "issue_slug": "other",
        "subject": "Constituent request",
        "body": "Use this for a topic or bill not listed—customize the message.",
        "email_body": "I am a constituent writing to ask you to support [describe the issue or bill]. This matters to me and my community. I'm counting on you to listen to your constituents and do the right thing.\n\nThank you for your time and your service.",
        "call_script": "Hi, I'm a constituent. I'm calling to ask you to support [describe the issue or bill]. Thank you for your time.",
    },
]
