import { useState, useEffect, useRef } from "react";
import type { Member, MemberBill } from "./api";
import {
  getScripts,
  getScript,
  generateScript,
  getContactStats,
  recordContactEvent,
  getMemberBills,
} from "./api";

interface Props {
  member: Member;
  onClose: () => void;
  initialIssue?: string;
  initialBillId?: string;
}

export default function ScriptFlow({ member, onClose, initialIssue, initialBillId }: Props) {
  const [scripts, setScripts] = useState<Array<{ id: number; title: string; billId?: string | null; issueSlug?: string | null }>>([]);
  const [selectedScriptId, setSelectedScriptId] = useState<number | null>(null);
  const [customIssue, setCustomIssue] = useState(initialIssue ?? "");
  const [emailBody, setEmailBody] = useState("");
  const [callScript, setCallScript] = useState("");
  const [subject, setSubject] = useState("");
  const [loading, setLoading] = useState(false);
  const [generateMessage, setGenerateMessage] = useState<string | null>(null);
  const [stats, setStats] = useState<{ last7Days: number; last30Days: number } | null>(null);
  const [issueForStats, setIssueForStats] = useState<string | null>(null);
  const [bills, setBills] = useState<MemberBill[]>([]);
  const [legislationExpanded, setLegislationExpanded] = useState(true);
  const [selectedBillNumber, setSelectedBillNumber] = useState<string | null>(null);
  const [copyFeedback, setCopyFeedback] = useState(false);
  const hasAutoGenerated = useRef(false);
  const copyFeedbackTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (copyFeedbackTimeout.current) clearTimeout(copyFeedbackTimeout.current);
    };
  }, []);

  useEffect(() => {
    if (initialIssue != null) setCustomIssue(initialIssue);
  }, [initialIssue]);

  useEffect(() => {
    getScripts().then((r) => setScripts(r.scripts));
  }, []);

  useEffect(() => {
    if (!member?.id) return;
    getContactStats(member.id).then((s) => {
      if (s) setStats({ last7Days: s.last7Days, last30Days: s.last30Days });
    });
  }, [member?.id]);

  useEffect(() => {
    if (!member?.id) return;
    getMemberBills(member.id).then((r) => setBills(r.bills ?? []));
  }, [member?.id]);

  // Auto-run generate when opening from "Contact about this bill" (initial issue or bill set)
  useEffect(() => {
    if (!member?.id || hasAutoGenerated.current) return;
    const hasInitial = (initialIssue ?? "").trim() !== "" || (initialBillId ?? "").trim() !== "";
    if (!hasInitial) return;
    hasAutoGenerated.current = true;
    runGenerate(null, (initialIssue ?? "").trim() || undefined, initialBillId ?? undefined);
  }, [member?.id, initialIssue, initialBillId]);

  async function loadSeedScript(id: number) {
    setSelectedScriptId(id);
    setSelectedBillNumber(null);
    setCustomIssue("");
    setGenerateMessage(null);
    const script = await getScript(id);
    if (script) {
      setIssueForStats(script.issueSlug || script.billId || null);
      if (script.issueSlug || script.billId) {
        getContactStats(member.id, script.billId ?? undefined, script.issueSlug ?? undefined).then((s) => {
          if (s) setStats({ last7Days: s.last7Days, last30Days: s.last30Days });
        });
      }
      // Generate detailed script via LLM instead of showing short seed body
      setEmailBody("");
      setCallScript("");
      setSubject("");
      await runGenerate(scripts.find((s) => s.id === id) ?? null, undefined, undefined);
    }
  }

  async function runGenerate(
    selected: { id: number; title: string; billId?: string | null; issueSlug?: string | null } | null,
    overrideIssueText: string | undefined,
    overrideBillId: string | undefined,
  ) {
    setLoading(true);
    setGenerateMessage(null);
    try {
      const res = await generateScript({
        memberId: member.id,
        issueText: (overrideIssueText ?? customIssue.trim()) || undefined,
        issueOrBillId: selected ? (selected.issueSlug || selected.billId || undefined) : (overrideBillId ?? initialBillId ?? undefined),
        issueTitle: selected ? selected.title : ((initialIssue ?? (overrideIssueText ?? customIssue.trim())) || undefined),
        scriptId: selected?.id ?? selectedScriptId ?? undefined,
      });
      setEmailBody(res.emailBody);
      setCallScript(res.callScript);
      setSubject(res.subject || "Constituent request");
      if (res.message) setGenerateMessage(res.message);
      setIssueForStats(selected ? (selected.issueSlug || selected.billId || null) : (overrideIssueText ?? customIssue.trim()) || null);
      if (overrideIssueText ?? customIssue.trim()) {
        getContactStats(member.id, undefined, overrideIssueText ?? customIssue.trim()).then((s) => {
          if (s) setStats({ last7Days: s.last7Days, last30Days: s.last30Days });
        });
      } else if (selected?.issueSlug || selected?.billId) {
        getContactStats(member.id, selected?.billId ?? undefined, selected?.issueSlug ?? undefined).then((s) => {
          if (s) setStats({ last7Days: s.last7Days, last30Days: s.last30Days });
        });
      }
    } catch (err) {
      setGenerateMessage(err instanceof Error ? err.message : "Failed to generate script. Is the backend running?");
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate() {
    const selected = selectedScriptId != null ? scripts.find((s) => s.id === selectedScriptId) : null;
    await runGenerate(selected, undefined, undefined);
  }

  function handleSendEmail() {
    const topic = issueForStats || customIssue.trim() || "general";
    recordContactEvent({
      memberId: member.id,
      topic: topic || undefined,
      contactType: "email",
    });
    const maxLen = 1800;
    let body = emailBody;
    if (body.length > maxLen) {
      body = body.slice(0, maxLen - 30) + "\n\n[Message truncated for mailto link.]";
    }
    const to = member.email ? encodeURIComponent(member.email) : "";
    const mailto = to
      ? `mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
      : `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailto;
  }

  function handleCall() {
    const topic = issueForStats || customIssue.trim() || "general";
    recordContactEvent({
      memberId: member.id,
      topic: topic || undefined,
      contactType: "call",
    });
  }

  function getMessageForClipboard(): string {
    return `Subject: ${subject}\n\n${emailBody}`;
  }

  function handleCopyMessage() {
    const text = getMessageForClipboard();
    navigator.clipboard.writeText(text).then(
      () => {
        setCopyFeedback(true);
        if (copyFeedbackTimeout.current) clearTimeout(copyFeedbackTimeout.current);
        copyFeedbackTimeout.current = setTimeout(() => {
          setCopyFeedback(false);
          copyFeedbackTimeout.current = null;
        }, 3000);
      },
      () => {},
    );
  }

  function handleOpenContactFormAndCopy() {
    if (member.contactFormUrl) {
      window.open(member.contactFormUrl, "_blank", "noopener,noreferrer");
    }
    handleCopyMessage();
  }

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "var(--color-overlay)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        padding: "var(--space-4)",
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: "var(--color-surface)",
          border: "1px solid var(--color-border)",
          boxShadow: "var(--shadow-lg)",
          borderRadius: "var(--radius-lg)",
          maxWidth: 560,
          width: "100%",
          maxHeight: "90vh",
          overflow: "auto",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ padding: "var(--space-4) var(--space-5)", borderBottom: "1px solid var(--color-border)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <h2 style={{ margin: 0, fontSize: "var(--text-lg)", color: "var(--color-text)" }}>Contact {member.name}</h2>
          <button
            type="button"
            onClick={onClose}
            style={{
              background: "none",
              border: "none",
              color: "var(--color-text-secondary)",
              fontSize: "1.5rem",
              cursor: "pointer",
              padding: 0,
              lineHeight: 1,
            }}
          >
            ×
          </button>
        </div>

        <div style={{ padding: "var(--space-4) var(--space-5)" }}>
          {stats != null && (stats.last7Days > 0 || stats.last30Days > 0) && (
            <p style={{ fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginBottom: "var(--space-4)" }}>
              {stats.last7Days} constituent{stats.last7Days !== 1 ? "s" : ""} contacted {member.name} about this topic in the last week.
              {stats.last30Days > 0 && ` ${stats.last30Days} in the last month.`}
            </p>
          )}

          {bills.length > 0 && (
            <section style={{ marginBottom: "1.25rem" }}>
              <button
                type="button"
                onClick={() => setLegislationExpanded((e) => !e)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  width: "100%",
                  padding: "0.5rem 0",
                  background: "none",
                  border: "none",
                  borderBottom: "1px solid var(--color-border)",
                  cursor: "pointer",
                  fontSize: "1rem",
                  color: "var(--color-text-secondary)",
                  textAlign: "left",
                }}
              >
                <span style={{ fontWeight: "var(--font-semibold)", color: "var(--color-text)" }}>Sponsored legislation</span>
                <span style={{ fontSize: "0.85rem" }}>{legislationExpanded ? "▼" : "▶"}</span>
              </button>
              {legislationExpanded && (
                <ul
                  style={{
                    margin: 0,
                    paddingLeft: "1.25rem",
                    fontSize: "0.9rem",
                    maxHeight: 220,
                    overflowY: "auto",
                    listStyle: "none",
                    marginTop: "0.5rem",
                  }}
                >
                  {bills.map((b, i) => (
                    <li key={i} style={{ marginBottom: 10 }}>
                      <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "0.5rem" }}>
                        {b.url ? (
                          <a href={b.url} target="_blank" rel="noopener noreferrer" style={{ color: "var(--color-primary)" }}>
                            {b.title || b.number || "Bill"}
                          </a>
                        ) : (
                          <span>{b.title || b.number || "Bill"}</span>
                        )}
                        {b.status && (
                          <span style={{ fontSize: "0.8rem", color: "#555" }}>{b.status}</span>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            setSelectedScriptId(null);
                            setCustomIssue(b.title || b.number || "this bill");
                            setGenerateMessage(null);
                            runGenerate(null, b.title || b.number || "this bill", b.number ?? undefined);
                          }}
                          style={{
                            padding: "0.25rem 0.5rem",
                            fontSize: "0.8rem",
                            border: "1px solid var(--color-primary)",
                            borderRadius: 4,
                            background: "transparent",
                            color: "var(--color-primary)",
                            cursor: "pointer",
                          }}
                        >
                          Contact about this bill
                        </button>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </section>
          )}

          <div style={{ marginBottom: "1rem" }}>
            <label style={{ display: "block", fontSize: "0.9rem", color: "var(--color-text-secondary)", marginBottom: 4 }}>
              Pick a topic or describe an issue
            </label>
            <select
              value={selectedScriptId ?? ""}
              onChange={(e) => {
                const v = e.target.value;
                if (v === "") {
                  setSelectedScriptId(null);
                  setSelectedBillNumber(null);
                  setGenerateMessage(null);
                  return;
                }
                loadSeedScript(Number(v));
              }}
              style={{
                width: "100%",
                padding: "0.5rem 0.75rem",
                fontSize: "1rem",
                border: "1px solid var(--color-border)",
                borderRadius: 6,
                background: "var(--color-bg)",
                color: "var(--color-text)",
                marginBottom: "0.5rem",
              }}
            >
              <option value="">Choose a topic…</option>
              {scripts.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.title}
                </option>
              ))}
            </select>
            {bills.length > 0 && (
              <div style={{ marginBottom: "0.5rem" }}>
                <label style={{ display: "block", fontSize: "0.85rem", color: "var(--color-text-secondary)", marginBottom: 4 }}>
                  Specific bill (optional)
                </label>
                <select
                  value={selectedBillNumber ?? ""}
                  onChange={(e) => {
                    const v = e.target.value;
                    if (v === "") {
                      setSelectedBillNumber(null);
                      setGenerateMessage(null);
                      return;
                    }
                    const b = bills.find((bill) => (bill.number ?? "") === v);
                    if (b) {
                      setSelectedScriptId(null);
                      setSelectedBillNumber(b.number ?? null);
                      setCustomIssue(b.title || b.number || "this bill");
                      setGenerateMessage(null);
                      runGenerate(null, b.title || b.number || "this bill", b.number ?? undefined);
                    }
                  }}
                  style={{
                    width: "100%",
                    padding: "0.5rem 0.75rem",
                    fontSize: "0.95rem",
                    border: "1px solid var(--color-border)",
                    borderRadius: 6,
                    background: "var(--color-bg)",
                    color: "var(--color-text)",
                  }}
                >
                  <option value="">None</option>
                  {bills.slice(0, 20).map((b, i) => (
                    <option key={i} value={b.number ?? ""} title={b.title || b.number || undefined}>
                      {b.number ? `${b.number}${b.status ? ` (${b.status})` : ""}` : (b.title || "Bill").slice(0, 50)}
                    </option>
                  ))}
                </select>
              </div>
            )}
            <input
              type="text"
              value={customIssue}
              onChange={(e) => setCustomIssue(e.target.value)}
              placeholder="Or type an issue (e.g. climate, healthcare)"
              style={{
                width: "100%",
                padding: "0.5rem 0.75rem",
                fontSize: "1rem",
                border: "1px solid var(--color-border)",
                borderRadius: 6,
                background: "var(--color-bg)",
                color: "var(--color-text)",
              }}
            />
            <button
              type="button"
              onClick={handleGenerate}
              disabled={loading}
              style={{
                marginTop: "0.5rem",
                padding: "0.5rem 1rem",
                fontSize: "0.9rem",
                border: "none",
                borderRadius: 6,
                background: "var(--color-primary)",
                color: "var(--color-surface)",
                cursor: loading ? "not-allowed" : "pointer",
              }}
            >
              {loading ? "Generating…" : "Generate script"}
            </button>
            {generateMessage && (
              <p style={{ fontSize: "0.85rem", color: "var(--color-error)", marginTop: "0.5rem", marginBottom: 0 }}>
                {generateMessage}
              </p>
            )}
          </div>

          {/* Call first: phone + script + instruction */}
          <section style={{ marginBottom: "var(--space-6)", paddingTop: "var(--space-2)", borderTop: "1px solid var(--color-border)" }}>
            <h3 style={{ margin: "0 0 var(--space-2)", fontSize: "var(--text-base)", fontWeight: "var(--font-semibold)", color: "var(--color-text)" }}>Call their office</h3>
            <p style={{ fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginBottom: "var(--space-2)", lineHeight: "var(--leading-snug)" }}>
              Staff usually answer. Use the script below (fill in [your city or state]) or your own words. If they ask for your address or zip, give it so they can log you as a constituent. You can say &quot;Just record my position&quot; if you don&apos;t need a callback.
            </p>
            {member.phone ? (
              <p style={{ marginTop: 0, marginBottom: "0.5rem" }}>
                Call: <strong>{member.phone}</strong>
                {member.phone && (
                  <a href={`tel:${member.phone}`} style={{ marginLeft: "0.5rem", fontSize: "0.9rem" }}>
                    (tap to call)
                  </a>
                )}
              </p>
            ) : member.url ? (
              <p style={{ marginTop: 0, marginBottom: "var(--space-2)", fontSize: "var(--text-sm)", color: "var(--color-text-secondary)" }}>
                Phone not on file;{" "}
                <a href={member.url} target="_blank" rel="noopener noreferrer">
                  find it on their website
                </a>
                .
              </p>
            ) : (
              <p style={{ marginTop: 0, marginBottom: "var(--space-2)", fontSize: "var(--text-sm)", color: "var(--color-text-secondary)" }}>
                Phone not on file.
              </p>
            )}
            <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginBottom: "var(--space-1)" }}>
              Call script (what to say)
            </label>
            <textarea
              value={callScript}
              onChange={(e) => setCallScript(e.target.value)}
              rows={3}
              style={{
                width: "100%",
                padding: "0.5rem 0.75rem",
                fontSize: "0.95rem",
                border: "1px solid var(--color-border)",
                borderRadius: "var(--radius-sm)",
                background: "var(--color-bg)",
                color: "var(--color-text)",
                resize: "vertical",
              }}
            />
            <button
              type="button"
              onClick={handleCall}
              style={{
                marginTop: "var(--space-2)",
                padding: "var(--space-2) var(--space-4)",
                fontSize: "var(--text-sm)",
                border: "none",
                borderRadius: "var(--radius-sm)",
                background: "var(--color-primary)",
                color: "var(--color-surface)",
                cursor: "pointer",
              }}
            >
              I&apos;m calling (record my contact)
            </button>
          </section>

          {/* Then: message + contact form / email */}
          <div style={{ marginBottom: "var(--space-4)" }}>
            <h3 style={{ margin: "0 0 var(--space-2)", fontSize: "var(--text-base)", fontWeight: "var(--font-semibold)", color: "var(--color-text)" }}>Or write to them</h3>
            <p style={{ fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginBottom: "var(--space-3)", lineHeight: "var(--leading-snug)" }}>
              We&apos;ll open their contact form and copy your message. Include your full name and address in the form so the office can verify you&apos;re a constituent—that&apos;s what makes your message count. Then paste, edit if you like, and submit.
            </p>
            <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginBottom: "var(--space-1)" }}>
              Your message (edit if you like—adding how this affects you or your community helps staff take it seriously)
            </label>
            <textarea
              value={emailBody}
              onChange={(e) => setEmailBody(e.target.value)}
              rows={4}
              style={{
                width: "100%",
                padding: "var(--space-2) var(--space-3)",
                fontSize: "var(--text-base)",
                border: "1px solid var(--color-border)",
                borderRadius: "var(--radius-sm)",
                background: "var(--color-bg)",
                color: "var(--color-text)",
                resize: "vertical",
              }}
            />
            <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "0.5rem", marginTop: "0.5rem" }}>
              {member.contactFormUrl ? (
                <button
                  type="button"
                  onClick={handleOpenContactFormAndCopy}
                  style={{
                    padding: "var(--space-2) var(--space-4)",
                    fontSize: "var(--text-sm)",
                    border: "none",
                    borderRadius: "var(--radius-sm)",
                    background: "var(--color-primary)",
                    color: "var(--color-surface)",
                    cursor: "pointer",
                  }}
                >
                  Open contact form & copy message (paste in the form)
                </button>
              ) : member.url ? (
                <>
                  <a
                    href={member.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      padding: "0.5rem 1rem",
                      fontSize: "0.9rem",
                      border: "none",
                      borderRadius: 6,
                      background: "var(--color-primary)",
                      color: "var(--color-surface)",
                      textDecoration: "none",
                    }}
                  >
                    Open their website
                  </a>
                  <button
                    type="button"
                    onClick={handleCopyMessage}
                    style={{
                      padding: "0.5rem 1rem",
                      fontSize: "0.9rem",
                      border: "1px solid var(--color-primary)",
                      borderRadius: 6,
                      background: "transparent",
                      color: "var(--color-primary)",
                      cursor: "pointer",
                    }}
                  >
                    Copy message
                  </button>
                </>
              ) : null}
              {member.email && (
                <button
                  type="button"
                  onClick={handleSendEmail}
                  style={{
                    padding: "0.5rem 1rem",
                    fontSize: "0.9rem",
                    border: "1px solid var(--color-primary)",
                    borderRadius: 6,
                    background: "transparent",
                    color: "var(--color-primary)",
                    cursor: "pointer",
                  }}
                >
                  Open email
                </button>
              )}
              {member.contactFormUrl && (
                <button
                  type="button"
                  onClick={handleCopyMessage}
                  style={{
                    padding: "0.5rem 1rem",
                    fontSize: "0.9rem",
                    border: "1px solid var(--color-border)",
                    borderRadius: 6,
                    background: "transparent",
                    color: "var(--color-text-secondary)",
                    cursor: "pointer",
                  }}
                >
                  Copy message
                </button>
              )}
            </div>
            {copyFeedback && (
              <p style={{ fontSize: "var(--text-sm)", color: "var(--color-primary)", marginTop: "var(--space-2)", marginBottom: 0 }}>
                Copied. Paste in the form that just opened.
              </p>
            )}
            {!member.email && !member.contactFormUrl && !member.url && (
              <p style={{ fontSize: "var(--text-sm)", color: "var(--color-text-secondary)", marginTop: "var(--space-2)", marginBottom: 0 }}>
                No contact link on file for this member.
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
